networks:
  app-network:
    driver: bridge

services:
  app:
    build: .
    ports:
      - "8181:8181"
    networks:
      - app-network
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=xamsamaternite
      - DB_USERNAME=root
      - DB_PASSWORD=root

  db:
    image: mysql
    networks:
      - app-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=xamsamaternite
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  db-data: